default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.109.0

variables:
  HUGO_ENV: production
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
