baseURL = "https://ateliers.prologin.org/"
languageCode = "fr-fr"
title = "Ateliers Prologin"
theme = "prologin"

# Allow having shortcode inside other shortcodes
[markup.goldmark.renderer]
unsafe = true
