baseURL = "https://ateliers.prologin.org/"
languageCode = "fr-fr"
title = "Ateliers Prologin"
theme = "prologin"

[markup]
    # Table of content level
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 1

    # Display lines number in simple code blocks
    [markup.highlight]
        lineNos = true

[params.style]
    primaryColor = "#131325"
    secondaryColor = "#dd3737"
    headerFont = "Courier"
    colorScheme = ["#dd3737", "#f59c2e", "#314658"]
    menuOffset = 10

# Allow having shortcode inside other shortcodes
[markup.goldmark.renderer]
    unsafe = true
