[build]
    publish = "public"
    command = "./build.sh && hugo"

[build.environment]
    HUGO_VERSION = "0.111.3"

[context.deploy-preview]
    command = "make -C themes/prologin deploy && hugo --buildDrafts"
